# Generated by Django 4.2.8 on 2023-12-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superMarket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/breeds/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
